doc[configure]:default python path and disable GCP/Hadoop/Cuda/OpenCL

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31,8 +31,9 @@ function bazel_clean_and_fetch() {
 while true; do
   fromuser=""
   if [ -z "$PYTHON_BIN_PATH" ]; then
-    default_python_bin_path=$(which python || which python3  || true)
-    read -p "Please specify the location of python. [Default is $default_python_bin_path]: " PYTHON_BIN_PATH
+    #default_python_bin_path=$(which python || which python3  || true)
+    default_python_bin_path="/usr/bin/python2.7"
+    #read -p "Please specify the location of python. [Default is $default_python_bin_path]: " PYTHON_BIN_PATH
     fromuser="1"
     if [ -z "$PYTHON_BIN_PATH" ]; then
       PYTHON_BIN_PATH=$default_python_bin_path
@@ -41,7 +42,7 @@ while true; do
   if [ -e "$PYTHON_BIN_PATH" ]; then
     break
   fi
-  echo "Invalid python path. ${PYTHON_BIN_PATH} cannot be found" 1>&2
+  echo "Invalid plthon path. ${PYTHON_BIN_PATH} cannot be found" 1>&2
   if [ -z "$fromuser" ]; then
     exit 1
   fi
@@ -55,19 +56,19 @@ if is_windows; then
   TF_NEED_OPENCL=0
 fi
 
-while [ "$TF_NEED_GCP" == "" ]; do
-  read -p "Do you wish to build TensorFlow with "\
-"Google Cloud Platform support? [y/N] " INPUT
-  case $INPUT in
-    [Yy]* ) echo "Google Cloud Platform support will be enabled for "\
-"TensorFlow"; TF_NEED_GCP=1;;
-    [Nn]* ) echo "No Google Cloud Platform support will be enabled for "\
-"TensorFlow"; TF_NEED_GCP=0;;
-    "" ) echo "No Google Cloud Platform support will be enabled for "\
-"TensorFlow"; TF_NEED_GCP=0;;
-    * ) echo "Invalid selection: " $INPUT;;
-  esac
-done
+#while [ "$TF_NEED_GCP" == "" ]; do
+#  read -p "Do you wish to build TensorFlow with "\
+#"Google Cloud Platform support? [y/N] " INPUT
+#  case $INPUT in
+#    [Yy]* ) echo "Google Cloud Platform support will be enabled for "\
+#"TensorFlow"; TF_NEED_GCP=1;;
+#    [Nn]* ) echo "No Google Cloud Platform support will be enabled for "\
+#"TensorFlow"; TF_NEED_GCP=0;;
+#    "" ) echo "No Google Cloud Platform support will be enabled for "\
+#"TensorFlow"; TF_NEED_GCP=0;;
+#    * ) echo "Invalid selection: " $INPUT;;
+#  esac
+#done
 
 if [ "$TF_NEED_GCP" == "1" ]; then
   ## Verify that libcurl header files are available.
@@ -85,19 +86,19 @@ else
   perl -pi -e "s,WITH_GCP_SUPPORT = (False|True),WITH_GCP_SUPPORT = False,s" tensorflow/core/platform/default/build_config.bzl
 fi
 
-while [ "$TF_NEED_HDFS" == "" ]; do
-  read -p "Do you wish to build TensorFlow with "\
-"Hadoop File System support? [y/N] " INPUT
-  case $INPUT in
-    [Yy]* ) echo "Hadoop File System support will be enabled for "\
-"TensorFlow"; TF_NEED_HDFS=1;;
-    [Nn]* ) echo "No Hadoop File System support will be enabled for "\
-"TensorFlow"; TF_NEED_HDFS=0;;
-    "" ) echo "No Hadoop File System support will be enabled for "\
-"TensorFlow"; TF_NEED_HDFS=0;;
-    * ) echo "Invalid selection: " $INPUT;;
-  esac
-done
+#while [ "$TF_NEED_HDFS" == "" ]; do
+#  read -p "Do you wish to build TensorFlow with "\
+#"Hadoop File System support? [y/N] " INPUT
+#  case $INPUT in
+#    [Yy]* ) echo "Hadoop File System support will be enabled for "\
+#"TensorFlow"; TF_NEED_HDFS=1;;
+#    [Nn]* ) echo "No Hadoop File System support will be enabled for "\
+#"TensorFlow"; TF_NEED_HDFS=0;;
+#    "" ) echo "No Hadoop File System support will be enabled for "\
+#"TensorFlow"; TF_NEED_HDFS=0;;
+#    * ) echo "Invalid selection: " $INPUT;;
+#  esac
+#done
 
 if [ "$TF_NEED_HDFS" == "1" ]; then
   # Update Bazel build configuration.
@@ -117,27 +118,27 @@ chmod a+x ${GEN_GIT_SOURCE}
 "${PYTHON_BIN_PATH}" ${GEN_GIT_SOURCE} --configure "${SOURCE_BASE_DIR}"
 
 ## Set up SYCL-related environment settings
-while [ "$TF_NEED_OPENCL" == "" ]; do
-  read -p "Do you wish to build TensorFlow with OpenCL support? [y/N] " INPUT
-  case $INPUT in
-    [Yy]* ) echo "OpenCL support will be enabled for TensorFlow"; TF_NEED_OPENCL=1;;
-    [Nn]* ) echo "No OpenCL support will be enabled for TensorFlow"; TF_NEED_OPENCL=0;;
-    "" ) echo "No OpenCL support will be enabled for TensorFlow"; TF_NEED_OPENCL=0;;
-    * ) echo "Invalid selection: " $INPUT;;
-  esac
-done
+#while [ "$TF_NEED_OPENCL" == "" ]; do
+#  read -p "Do you wish to build TensorFlow with OpenCL support? [y/N] " INPUT
+#  case $INPUT in
+#    [Yy]* ) echo "OpenCL support will be enabled for TensorFlow"; TF_NEED_OPENCL=1;;
+#    [Nn]* ) echo "No OpenCL support will be enabled for TensorFlow"; TF_NEED_OPENCL=0;;
+#    "" ) echo "No OpenCL support will be enabled for TensorFlow"; TF_NEED_OPENCL=0;;
+#    * ) echo "Invalid selection: " $INPUT;;
+#  esac
+#done
 
 ## Set up Cuda-related environment settings
 
-while [ "$TF_NEED_CUDA" == "" ]; do
-  read -p "Do you wish to build TensorFlow with GPU support? [y/N] " INPUT
-  case $INPUT in
-    [Yy]* ) echo "GPU support will be enabled for TensorFlow"; TF_NEED_CUDA=1;;
-    [Nn]* ) echo "No GPU support will be enabled for TensorFlow"; TF_NEED_CUDA=0;;
-    "" ) echo "No GPU support will be enabled for TensorFlow"; TF_NEED_CUDA=0;;
-    * ) echo "Invalid selection: " $INPUT;;
-  esac
-done
+#while [ "$TF_NEED_CUDA" == "" ]; do
+#  read -p "Do you wish to build TensorFlow with GPU support? [y/N] " INPUT
+#  case $INPUT in
+#    [Yy]* ) echo "GPU support will be enabled for TensorFlow"; TF_NEED_CUDA=1;;
+#    [Nn]* ) echo "No GPU support will be enabled for TensorFlow"; TF_NEED_CUDA=0;;
+#    "" ) echo "No GPU support will be enabled for TensorFlow"; TF_NEED_CUDA=0;;
+#    * ) echo "Invalid selection: " $INPUT;;
+#  esac
+#done
 
 ## add FPGA support choice
 while [ "$TF_NEED_FPGA" == "" ]; do
